SELECT DISTINCT
      PRLA.LINE_NUMBER,
      PRLA.ITEM_DESCRIPTION,
      PRLA.QUANTITY,
      PRLA.DESTINATION_TYPE_CODE UMO,
      --DECODE(PRLA.UOM_CODE,'UN','UNIT',PRLA.UOM_CODE) UMO,
      PRHA.REQUISITION_NUMBER,
      ECV.CATEGORY_NAME ITEM_CODE,
	 -- DECODE(PRLA.DESTINATION_TYPE_CODE,'EXPENSE',0,NVL(DTLS.TRANSACTION_QUANTITY, 0)) STORE_Q,
	 DECODE(PRLA.DESTINATION_TYPE_CODE,'EXPENSE',0,(Select (NVL(DTLS.TRANSACTION_QUANTITY, 0)) from INV_ONHAND_QUANTITIES_DETAIL DTLS where 1=1  
		AND DTLS.INVENTORY_ITEM_ID     =ESIB.INVENTORY_ITEM_ID and rownum=1)) as STORE_Q,
	 
	 PRLA.ITEM_ID,--100000002026984
	 ESIB.INVENTORY_ITEM_ID,
     -- SUM(NVL(DTLS.TRANSACTION_QUANTITY, 0)) Onhand_qty,
	 (Select SUM(NVL(DTLS.TRANSACTION_QUANTITY, 0)) from INV_ONHAND_QUANTITIES_DETAIL DTLS where 1=1  
		AND DTLS.INVENTORY_ITEM_ID     =ESIB.INVENTORY_ITEM_ID	 AND DTLS.organization_id = 300000003131182) as Onhand_qty,--
      TO_CHAR(PRHA.CREATION_DATE,'DD-MM-YYYY') Requisition_Date,
	  PPN.FULL_NAME Requestor,
	  HLA.LOCATION_NAME Deliver_To_Location,
      PRLA.SOURCE_SUBINVENTORY Source_SubInventory,
   	  HAOU.NAME Source_Organization
      /* (select max(FULL_NAME) from PER_PERSON_NAMES_F 
	  where  PERSON_ID=PRHA.PREPARER_ID and rownum=1)"Requisition_requestor" */
FROM 
    POR_REQUISITION_HEADERS_ALL PRHA,
    POR_REQUISITION_LINES_ALL PRLA,
    EGP_CATEGORIES_VL ECV,
    EGP_SYSTEM_ITEMS_B ESIB,
    --INV_ONHAND_QUANTITIES_DETAIL DTLS,
	PER_PERSON_NAMES_F PPN,
    HR_LOCATIONS_ALL  HLA,
	HR_ALL_ORGANIZATION_UNITS_X  HAOU
WHERE 1=1
       AND PRLA.REQUISITION_HEADER_ID =PRHA.REQUISITION_HEADER_ID
       AND PRLA.CATEGORY_ID           =ECV.CATEGORY_ID
       AND PRLA.ITEM_ID               =ESIB.INVENTORY_ITEM_ID
      -- AND DTLS.INVENTORY_ITEM_ID     =ESIB.INVENTORY_ITEM_ID
       AND (PRHA.REQUISITION_NUMBER IN(:P_REQ_NUMBER) OR 'ALL' IN (:P_REQ_NUMBER ||'ALL')) 
      AND PPN.PERSON_ID(+)           = PRHA.PREPARER_ID
      -- AND PRHA.REQUISITION_NUMBER =256
	  AND PPN.NAME_TYPE='GLOBAL'
	   AND PRLA.DELIVER_TO_LOCATION_ID =HLA.LOCATION_ID 
	   AND PRLA.SOURCE_ORGANIZATION_ID=HAOU.ORGANIZATION_ID(+)
/*GROUP BY
        PRLA.LINE_NUMBER,
        PRLA.ITEM_DESCRIPTION,
        PRLA.QUANTITY,
        PRLA.DESTINATION_TYPE_CODE,
        --PRLA.UOM_CODE,
        PRHA.REQUISITION_NUMBER,
        ECV.CATEGORY_NAME,
        PRHA.CREATION_DATE,
       -- PPN.Full_name,
        HLA.LOCATION_NAME,
        PRLA.SOURCE_SUBINVENTORY,
   	    HAOU.NAME
		--,
--NVL(DTLS.TRANSACTION_QUANTITY, 0)*/
		 
ORDER BY
PRHA.REQUISITION_NUMBER,
PRLA.LINE_NUMBER